spring:
  application.name: random-image
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:random-image-db
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: create
    show-sql: true


